export const EGYPT_GOVERNORATES: Record<string, string[]> = {
  Cairo: [
    "Maadi",
    "Helwan",
    "Nasr City",
    "Zamalek",
    "Downtown",
    "Garden City",
    "Mohandessin",
    "Dokki",
    "Abbasya",
    "Shubra",
    "Ain Shams",
    "El-Marg",
    "El-Salam",
    "Badr City",
    "New Cairo",
    "El-Obour",
    "Shorouk",
  ],
  Alexandria: [
    "Montaza",
    "Sidi Gaber",
    "Stanley",
    "Alexandria Downtown",
    "Raml Station",
    "El-Max",
    "Agami",
    "Borg El Arab",
    "El-Dekheila",
  ],
  Giza: [
    "Dokki",
    "Mohandessin",
    "Agouza",
    "Imbaba",
    "Giza Downtown",
    "Haram",
    "Faisal",
    "El-Monib",
    "Sheikh Zayed",
    "6th of October",
    "El-Hawamdeya",
    "Badrasheen",
  ],
  "Port Said": ["Port Said Downtown", "El-Manakh", "El-Gamal", "El-Zohour"],
  Suez: ["Suez Downtown", "El-Arbaeen", "El-Ganayen", "El-Tal El-Kebir"],
  Luxor: [
    "Luxor Downtown",
    "Karnak",
    "West Bank",
    "Esna",
    "Armant",
    "El-Tod",
  ],
  Aswan: [
    "Aswan Downtown",
    "Elephantine",
    "Kom Ombo",
    "Edfu",
    "Daraw",
    "Nubia",
  ],
  Asyut: [
    "Asyut Downtown",
    "El-Zohour",
    "El-Moallem",
    "El-Walideya",
    "Dayrout",
  ],
  Beheira: [
    "Damanhour",
    "Kafr El-Dawar",
    "Rashid",
    "Edku",
    "Abu El-Matamir",
    "El-Mahmoudia",
  ],
  "Beni Suef": [
    "Beni Suef Downtown",
    "El-Fashn",
    "Beba",
    "Nasser",
    "El-Wasta",
  ],
  Dakahlia: [
    "Mansoura",
    "Talkha",
    "Mit Ghamr",
    "Dikirnis",
    "Aga",
    "El-Senbellawein",
  ],
  Damietta: [
    "Damietta Downtown",
    "New Damietta",
    "El-Zarka",
    "Faraskour",
    "Kafr Saad",
  ],
  Faiyum: [
    "Faiyum City",
    "Ebshawai",
    "Sinnuris",
    "Itsa",
    "Tamiya",
    "Yusuf El-Siddik",
  ],
  Gharbia: [
    "Tanta",
    "El-Mahalla El-Kubra",
    "Kafr El-Zayat",
    "El-Santa",
    "Zeifta",
    "El-Gharbia",
  ],
  Ismailia: [
    "Ismailia Downtown",
    "El-Tal El-Kebir",
    "Abu Swayr",
    "El-Qantara",
  ],
  "Kafr El Sheikh": [
    "Kafr El Sheikh",
    "Desouk",
    "Baltim",
    "El-Hamool",
    "Bella",
  ],
  Matruh: [
    "Matruh Downtown",
    "Marsa Matruh",
    "El-Dabaa",
    "El-Negaila",
    "Sidi Barrani",
  ],
  Minya: [
    "Minya Downtown",
    "El-Minya El-Gedida",
    "Mallawi",
    "Deir Mawas",
    "Abu Qurqas",
  ],
  Monufia: [
    "Shebin El-Kom",
    "Menouf",
    "Tala",
    "El-Bagour",
    "Quesna",
  ],
  "New Valley": ["El-Kharga", "El-Dakhla", "El-Farafra", "El-Bahariya"],
  "North Sinai": [
    "El-Arish",
    "Rafah",
    "Sheikh Zuweid",
    "El-Hassana",
    "El-Quseima",
  ],
  Qalyubia: [
    "Banha",
    "El-Qanater",
    "Shubra El-Kheima",
    "El-Khanka",
    "Kafr Shukr",
  ],
  Qena: ["Qena Downtown", "Luxor (part)", "Naga Hammadi", "El-Dishna"],
  "Red Sea": ["Hurghada", "Safaga", "El-Quseir", "Sharm El-Sheikh (part)"],
  Sharqia: [
    "Zagazig",
    "Belbeis",
    "Abu Hammad",
    "El-Husseiniya",
    "Minya El-Qamh",
  ],
  Sohag: ["Sohag Downtown", "Akhmim", "Girga", "El-Balyana", "El-Maragha"],
  "South Sinai": [
    "Sharm El-Sheikh",
    "Dahab",
    "Nuweiba",
    "St. Catherine",
    "El-Tor",
  ],
};

export const EGYPT_GOVERNORATE_NAMES = Object.keys(EGYPT_GOVERNORATES);